---
# Red Hat Course to deploy OpenStack hosts with dynamic variables
- name: OpenStack Deployment through a Jumpbox
  hosts: jumpbox
  vars_files:
    - osp_network_var.yml
  vars:
    cloud_name: ospcloud
  roles:
    - osp-network
    - osp-keypair
    - osp-securitygroup
  tasks:
  # Create Fronend Instance
    - name: Create frontend instance
      include_role:
        name: osp-instances
        vars_from: frontend.yml
  # Create App1 server
    - name: Create app1 instance
      include_role:
        name: osp-instances
        vars_from: app1.yml
  # Create App2 server
    - name: Create app2 instance
      include_role:
        name: osp-instances
        vars_from: app2.yml
  # Create DB server
    - name: Create db instance
      include_role:
        name: osp-instances
        vars_from: db.yml
  # Gather Facts for use with Dynamic Inventory
    - name: Gather facts
      include_role:
        name: osp-facts
      tags:
        - test_inventory
...
