---
- name: Generate local key files on Jumpbox
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa
- name: Install Keys on Openstack
  os_keypair:
    cloud: "{{ cloud_name }}"
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
...
